// Constructor - creating a Date object
const currentDate = new Date();

// Accessor Methods
const dayOfMonth = currentDate.getDate();
const dayOfWeek = currentDate.getDay();
const currentYear = currentDate.getFullYear();
const currentHour = currentDate.getHours();
const currentMilliseconds = currentDate.getMilliseconds();
const currentMinutes = currentDate.getMinutes();
const currentMonth = currentDate.getMonth();
const currentSeconds = currentDate.getSeconds();
const currentTimeInMilliseconds = currentDate.getTime();
const timezoneOffset = currentDate.getTimezoneOffset();
const utcDate = currentDate.getUTCDate();
const utcDay = currentDate.getUTCDay();
const utcFullYear = currentDate.getUTCFullYear();
const utcHours = currentDate.getUTCHours();
const utcMilliseconds = currentDate.getUTCMilliseconds();
const utcMinutes = currentDate.getUTCMinutes();
const utcMonth = currentDate.getUTCMonth();
const utcSeconds = currentDate.getUTCSeconds();

// Setter Methods
currentDate.setDate(10);
currentDate.setFullYear(2025);
currentDate.setHours(15);
currentDate.setMilliseconds(500);
currentDate.setMinutes( );
currentDate.setMonth(6);
currentDate.setSeconds(45);
currentDate.setTime(1640990000000);
currentDate.setUTCDate(15);
currentDate.setUTCFullYear(2026);
currentDate.setUTCHours(12);
currentDate.setUTCMilliseconds(250);
currentDate.setUTCMinutes(20);
currentDate.setUTCMonth(11);
currentDate.setUTCSeconds(55);

// Conversion Methods
const dateString = currentDate.toDateString();
const isoString = currentDate.toISOString();
const jsonString = currentDate.toJSON();
const localeDateString = currentDate.toLocaleDateString();
const localeTimeString = currentDate.toLocaleTimeString();
const localeString = currentDate.toLocaleString();
const stringRepresentation = currentDate.toString();
const timeString = currentDate.toTimeString();
const utcString = currentDate.toUTCString();

// Displaying the results
document.write("Current Date:", currentDate);
document.write("<br>"); 
document.write("Day of Month:", dayOfMonth);
document.write("<br>");
document.write("Day of Week:", dayOfWeek);
document.write("<br>");
document.write("Current Year:", currentYear);
document.write("<br>");
document.write("Current Hour:", currentHour);
document.write("<br>");
document.write("Current Milliseconds:", currentMilliseconds);
document.write("<br>");
document.write("Current Minutes:", currentMinutes);
document.write("<br>");
document.write("Current Month:", currentMonth);
document.write("<br>");
document.write("Current Seconds:", currentSeconds);
document.write("<br>");
document.write("Current Time in Milliseconds:", currentTimeInMilliseconds);
document.write("<br>");
document.write("Timezone Offset:", timezoneOffset);
document.write("<br>");
document.write("UTC Date:", utcDate);
document.write("<br>");
document.write("UTC Day:", utcDay);
document.write("<br>");
document.write("UTC Full Year:", utcFullYear);
document.write("<br>");
document.write("UTC Hours:", utcHours);
document.write("<br>");
document.write("UTC Milliseconds:", utcMilliseconds);
document.write("<br>");
document.write("UTC Minutes:", utcMinutes);
document.write("<br>");
document.write("UTC Month:", utcMonth);
document.write("<br>");
document.write("UTC Seconds:", utcSeconds);
document.write("<br>");
document.write("\nSetting Methods Applied:\n", currentDate);
document.write("<br>");
document.write("\nDate after applying Conversion Methods:\n", dateString);
document.write("<br>");
document.write(isoString);
document.write("<br>");
document.write(jsonString);
document.write("<br>");
document.write(localeDateString);
document.write("<br>");
document.write(localeTimeString);
document.write("<br>");
document.write(localeString);
document.write("<br>");
document.write(stringRepresentation);
document.write("<br>");
document.write(timeString);
document.write("<br>");
document.write(utcString);
document.write("<br>");